= Introduction & Quick-start

Most of us are into free wireless mesh networks. We're fascinated by the idea of
deploying a bunch of OpenWRT routers, that magically connect to each other
to span large mesh cloud.

Unfortunately, doing so is very hard - the various different options for mesh routing protocols
and network designs can be overwhelming.


Many community networks deploy complex configurations. They release
custom firmware blobs using self-written scripts to customize OpenWRT images.
Usually, these firmware blobs are tight to a specific network by including network addresses or wifi identifiers.

Some Freifunk firmware files even include vpn-server-addresses, rendering them useless for other communities or
people living just a few kilometers away.

Here, configuration becomes opaque and thus hard to understand: It's buried in binary images using custom
software and different, sometimes hackish startup-scripts.

Build systems such as Gluon provide a heavy-weight abstraction to OpenWRT.
By creating a Domain-Specific-Language (DSL), all relevant OpenWRT settings are duplicated into a site-model,
which is then used to describe a specific community network. Although not having explicit restrictions,
this site-model focuses on backend-server driven networks, somewhat missing the point of a wifi mesh network.
Very little changes to the configuration require a build using the full OpenWRT buildroot.

Node-config is trying to jump in here by providing a comprehensible configuration.
Without having a shiny user interface in its core, node-config is focusing on network enthusiasts.
It explains all necessary OpenWRT settings for a simple wifi mesh, while providing a complete and easy-to-use setup.

This documentation is devided into tree chapters: <<_introduction_quick_start>>
 provides an overview including
a hands-on. It helps to get node-config running in a few minutes. The chapter
<<_configuration_in_node_config>> takes a deep dive into the configuration:
It outlines all things done to an OpenWRT router by node-config.
The last chapter <<_advanced_topics>> highlights the background.
It illustrates node-config's design considerations and explains the concepts in use.
Building packages and firmware is also addressed in the last chapter.

Let's get started.

== What node-config is

Node-config is just a _bunch of uci configuration files including a scripts to apply them_. It is copied to
plain OpenWRT routers running OpenWRT 18.06 and merged into the existing configuration. It configures routing, network- and wireless interfaces as
well as network services such as dhcp and radv.

It spans a mesh network using _both babel and batman-adv_ to provide roaming and
hierarchical routing capabilities. The network is IPv4 and IPv6 dual-stack.


[NOTE]
====
.You can use and understand node-config as:
- An elaborate example for an OpenWRT mesh configuration
- A kickstarter or template for wifi mesh networks without a central vpn (i.e. servers)
- A way for building supernodish nodes in gluon based Freifunk networks to get rid of servers
- A lean baseline for testing new architectures and services (i.e. l3roamd)
====

A git-repository is available at  https://github.com/yanosz/node-config -
for help and discussions please subscribe to the
https://lists.freifunk.net/mailman/listinfo/wlanware-freifunk.net[wlanware mailing list].


== Quick-start

You need https://downloads.openwrt.org[OpenWRT 18.06] installed on a router and enough free flash space (~2 MB).
The router has to be connected to the internet (wan port) an to your computer (pc or laptop using the lan port)

It helps to be familiar with a unix terminal (i.e. Mac OS, Linux)
since you need to use ssh to connect to your router. In addition, git is required:

.On your computer execute:

[#src-listing]
[source,bash]
----
git clone https://github.com/yanosz/node-config.git
cd node-config; scp -r freifunk root@192.168.1.1:/lib
ssh root@192.168.1.1 /lib/freifunk/install.sh
----

It is assumed, that your router is reachable at `192.168.1.1` (OpenWRT default). Using `git`, `scp` and `ssh`
node-config is cloned and then copied to your router. It is applied using <<_install_sh>>.


[WARNING]
====
1. _Set a password_ - your router will be reachble using ssh.
2. When executing `/lib/freifunk/install.sh` you are asked for one IPv4 (/24) and one IPv6 (/64) network.
These networks are distributed using dhcp and radv and _have to be unique_.
You _must not share a subnet among routers_. Using distinct RFC1918 ranges and IPv6 unique local addresses (ULA)
is usually the way to go. Please mind bookkeeping.
====

== Using packages

Packages can be used _instead of copying the filesystem tree_ using git and scp.

For testing, opkg packages are available at: https://kbu.freifunk.net/files/node-config/. Packages are built
using an https://git.kbu.freifunk.net/yanosz/node-config-feed[additional project integrated into GitLab CI].

.To install the packages open a ssh session to your router and execute:

[#src-listing]
[source,bash]
----
wget -O /etc/opkg/keys/cca6643a8ac2f277 http://opkg.kbu.freifunk.net/node-config/cca6643a8ac2f277
echo "src/gz nc http://opkg.kbu.freifunk.net/node-config/packages" >> /etc/opkg/customfeeds.conf
opkg update
opkg install node-config node-config-openvpn node-config-pptp
----
_Reboot the router_, after installing the packages.
For setting IPv4 and IPv6 networks open a new ssh session execute `/lib/freifunk/set_ip.sh`.
When executing `opkg install node-config`, core components are installed, only - openvpn and pptp are not available.

[CAUTION]
====
1. Set a password - your router will be reachable using ssh
2. Make sure, that `/etc/opkg/keys/cca6643a8ac2f277` matches the key available at
https://kbu.freifunk.net/files/node-config/cca6643a8ac2f277 - the download _is not using TLS_.
3. The public key for `cca6643a8ac2f277` is availble in our Gitlab CI and may be easily become compromised.
Consider using you own key when using packages. For details see <<_makefiles>>.
====

== Internet Sharing

=== Direct Exit
To share the routers WAN uplink in the mesh cloud, you have to enable it.

.Open a ssh session to your router and execute:

[#src-listing]
[source,bash]
----
uci set network.internet_share.disabled=0
uci set network.internet_share6.disabled=0
uci firewall.freifunk_internet.dest='wan'
uci commit firewall
uci commet network
/etc/init.d/firewall restart
/etc/init.d/network restart
----

NOTE: By enabling `internet_share` and `internet_share6`, WAN routes will be copied to the
mesh routing table. `uci firewall.freifunk_internet.dest='wan'` enables forwarding.

=== Using a VPN provider
To use a vpn tunnel (i.e. mullvad),
you can use a configuration in `/lib/freifunk/vpn` and activate it by editing `/etc/config/openvpn`.
See <<__etc_config_openvpn>> for details.

TIP: If you want to use a provider not included in
`/lib/freifunk/vpn`, you can place your provider's configuration there.
Mind adding `route-nopull`, `script-security 2` and `up /lib/freifunk/vpn/up.sh` for default route handling.
Have a look at existing VPN configurations for example. Also mind setting `dev vpn-nat` to use
the correct network interface.

== Git directory structure

All configuration can be found in `/freifunk/initial_configuration`. Other directories contain scripts,
build files and documentation.

|===
|Path |Contents
|`/`
| Directory root, including readme's, the project's Makefile and CI-configuration
|`/doc`
| Documentation including the asciidoc source of this manual
|`/freifunk`
| Configuration including scripts
|`/freifunk/initial_configuration`
| OpenWRT configuration (uci)
|`/freifunk/lib`
| Shared routines for scripts
|`/freifunk/vpn`
| OpenVPN exit configuration for different providers
|`/lede_built/node-config`
| Makefiles and other files for creating OpenWRT packages
|===
